#!/bin/sh
# chmod u+x run

GUNICORN=/usr/local/bin/gunicorn
ROOT=/root/app
PID=/var/run/gunicorn.pid

APP=app:app

if [ -f $PID ]; then rm $PID; fi

cd $ROOT
exec $GUNICORN -c $ROOT/gunicorn.conf.py --pid=$PID $APP